=== dshatilov/xml_knt/files/classification.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:for="format-properties">
  <xs:import namespace="format-properties" schemaLocation="fp.xsd"/>
  <xs:element name="classification" type="classificationType"/>
  <xs:complexType name="variantType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="id" use="required"/>
        <xs:attribute ref="for:ВерФОтч"/>
        <xs:attribute type="xs:string" name="contentType" use="optional"/>
        <xs:attribute ref="for:ТипИнф"/>
        <xs:attribute ref="for:ВерсФорм"/>
        <xs:attribute type="xs:string" name="ТипИнф" use="optional"/>
        <xs:attribute type="xs:string" name="periods" use="optional"/>
        <xs:attribute type="xs:string" name="period-modifiers" use="optional"/>
        <xs:attribute type="xs:string" name="ВерсФорм" use="optional"/>
        <xs:attribute ref="for:КНД" />
        <xs:attribute type="xs:string" name="form-modifiers" use="optional"/>
        <xs:attribute type="xs:string" name="shortName" use="optional"/>
        <xs:attribute type="xs:string" name="name" use="optional"/>
        <xs:attribute type="xs:string" name="restriction-quarte" use="optional"/>
        <xs:attribute type="xs:string" name="valid" use="optional"/>
        <xs:attribute ref="for:version" />
        <xs:attribute ref="for:XmlRootElement" />
        <xs:attribute ref="for:РАСЧЕТ_ПО_ВЗНОСАМ_ПО_ДОПОЛНИТЕЛЬНОМУ_ТАРИФУ_ЛЭВС" />
        <xs:attribute ref="for:РАСЧЕТ_ПО_ВЗНОСАМ_НА_ДОПОЛНИТЕЛЬНОЕ_СОЦИАЛЬНОЕ_ОБЕСПЕЧЕНИЕ" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="formatType">
    <xs:sequence>
      <xs:element type="variantType" name="variant" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="id" use="required"/>
    <xs:attribute ref="for:КНД" />
    <xs:attribute type="xs:string" name="shortName" use="optional"/>
    <xs:attribute type="xs:string" name="name" use="optional"/>
    <xs:attribute type="xs:string" name="periods" use="optional"/>
    <xs:attribute type="xs:string" name="form-modifiers" use="optional"/>
    <xs:attribute type="xs:string" name="synonyms" use="optional"/>
    <xs:attribute type="xs:string" name="period-modifiers" use="optional"/>
    <xs:attribute type="xs:string" name="restriction-quarter" use="optional"/>
    <xs:attribute ref="for:ТипИнф" />
    <xs:attribute ref="for:code" />
    <xs:attribute type="xs:string" name="ОКУД" use="optional"/>
    <xs:attribute ref="for:shifr" />
    <xs:attribute ref="for:КФО" />
    <xs:attribute ref="for:НомФорм" />
    <xs:attribute ref="for:НаимФОтч" />
    <xs:attribute ref="for:ТипДокумента" />
    <xs:attribute type="xs:string" name="alias" use="optional"/>
    <xs:attribute ref="for:РАСЧЕТ_ПО_СТРАХОВЫМ_ВЗНОСАМ_НА_ОПС_И_ОМС_ПЛАТЕЛЬЩИКАМИ_ПРОИЗВОДЯЩИМИ_ВЫПЛАТЫ_ФЛ" />
    <xs:attribute ref="for:РАСЧЕТ_ПО_СТРАХОВЫМ_ВЗНОСАМ_НА_ОПС_И_ОМС_ПЛАТЕЛЬЩИКАМИ_СВ_ПРОИЗВОДЯЩИМИ_ВЫПЛАТЫ_ФЛ_НАЧИНАЯ_С_2012_ГОДА" />
    <xs:attribute ref="for:РАСЧЕТ_ПО_СТРАХОВЫМ_ВЗНОСАМ_НА_ОПС_И_ОМС_ПЛАТЕЛЬЩИКАМИ_НЕ_ПРОИЗВОДЯЩИМИ_ВЫПЛАТЫ_ФЛ" />
    <xs:attribute ref="for:ВидФормы" />
    <xs:attribute ref="for:filename" />
    <xs:attribute type="xs:string" name="code" use="optional"/>
  </xs:complexType>
  <xs:complexType name="groupType">
    <xs:sequence>
      <xs:element type="formatType" name="format" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="id" use="required"/>
    <xs:attribute type="xs:string" name="name" use="required"/>
  </xs:complexType>
  <xs:complexType name="classificationType">
    <xs:sequence>
      <xs:element type="groupType" name="group" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== dshatilov/xml_knt/files/classification.xml
<?xml version="1.0" encoding="utf-8"?>
<classification xmlns:fp="format-properties" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:noNamespaceSchemaLocation="classification.xsd">
  <group id="1" name="Налоговая отчетность">
    <format id="1" fp:КНД="1110005" shortName="Сбор за пользование объектами водных биологических ресурсов" name="Сведения о полученной лицензии на пользование объектами водных биологических ресурсов, суммах сбора за пользование объектами водных биологических ресурсов, подлежащих уплате в виде разового и регулярных взносов" periods="1" form-modifiers="1">
      <variant id="1" fp:ВерФОтч="3.00000" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
    </format>
    <format id="2" fp:КНД="1110006" shortName="Сбор за пользование объектами животного мира" name="Сведения о полученной лицензии (разрешении) на пользование объектами животного мира, суммах сбора за пользование объектами животного мира, подлежащих уплате, и суммах фактического сбора" periods="1" form-modifiers="1">
      <variant id="1" fp:ВерФОтч="3.00000" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
    </format>
    <format id="3" fp:КНД="1110011" shortName="Сбор за пользование объектами водных биологических ресурсов" name="Сведения о полученных лицензиях (разрешениях) на пользование объектами водных биологических ресурсов, суммах сбора за пользование объектами водных биологических ресурсов, подлежащих уплате в виде разового и регулярных взносов"  periods="1" form-modifiers="1">
      <variant id="1" fp:ВерФОтч="3.00001" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
    </format>
    <format id="4" fp:КНД="1110012" shortName="Сбор за пользование объектами животного мира" name="Сведения о полученных лицензиях (разрешениях) на пользование объектами животного мира, суммах сбора за пользование объектами животного мира, подлежащих уплате, и суммах фактически уплаченного сбора" periods="1" form-modifiers="1">
      <variant id="1" fp:ВерФОтч="3.00001" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
    </format>
    <format id="5" fp:КНД="1110018" shortName="Сведения о среднесписочной численности" name="Сведения о среднесписочной численности работниковза предшествующий календарный год" periods="1" synonyms="ССЧ">
      <variant id="1" fp:ВерсФорм="4.01" contentType="Xml" fp:ТипИнф="СВЕДСРСПИСЧИСЛ" />
    </format>
    <format id="6" fp:КНД="1111004" shortName="Сообщение об открытии/закрытии счета индивидуальным предпринимателем" name="Сообщение об открытии/закрытии счета индивидуальным предпринимателем">
      <variant id="1" fp:ВерФОтч="2.00000" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
    </format>
    <format id="7" fp:КНД="1111007" shortName="Сообщение об открытии/закрытии счета юридическим лицом" name="Сообщение об открытии/закрытии счета юридическим лицом">
      <variant id="1" fp:ВерФОтч="2.00000" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
    </format>
    <format id="8" fp:КНД="1111030" shortName="Отчет об использовании федеральных спецмарок" name="Отчет об использовании федеральных специальных марок">
      <variant id="1" fp:ВерФОтч="2.00" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
    </format>
    <format id="9" fp:КНД="1111033" shortName="Заявка на федеральные спецмарки" name="Заявка на федеральные специальные марки для маркировки алкогольной продукции">
      <variant id="1" fp:ВерФОтч="2.01" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
    </format>
    <format id="10" fp:КНД="1151001" shortName="НДС" name="Налоговая декларация по налогу на добавленную стоимость" periods="110" form-modifiers="1">
      <variant id="1" fp:ВерФОтч="2.00003" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
      <variant id="2" fp:ВерФОтч="3.00000" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
      <variant id="3" fp:ВерФОтч="3.00001" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
      <variant id="4" fp:ВерФОтч="3.00002" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
      <variant id="5" fp:ВерФОтч="3.00003" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
      <variant id="6" fp:ВерФОтч="3.00004" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
      <variant id="7" fp:ВерФОтч="3.00005" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
      <variant id="8" fp:ВерФОтч="3.00006" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
      <variant id="9" fp:ВерсФорм="5.01" contentType="Xml" ТипИнф="ОТЧЕТНОСТЬ5.00" periods="10" period-modifiers="10"/>
      <variant id="10" fp:ВерсФорм="5.02" contentType="Xml" ТипИнф="ОТЧЕТНОСТЬ5.00" periods="10" period-modifiers="1010"/>
    </format>
    <format id="11" fp:КНД="1151002" shortName="НДС по ставке 0%" name="Налоговая декларация по налогу на добавленную стоимость по налоговой ставке 0%" periods="110" form-modifiers="1">
      <variant id="1" fp:ВерФОтч="2.00001" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
      <variant id="2" fp:ВерФОтч="3.00000" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
      <variant id="3" fp:ВерФОтч="3.00001" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
      <variant id="4" fp:ВерФОтч="3.00002" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
      <variant id="5" fp:ВерФОтч="3.00003" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
    </format>
    <format id="12" fp:КНД="1151003" shortName="Акцизы на подакцизные товары" name="Налоговая декларация по акцизам на подакцизные товары, за исключением нефтепродуктов и табачных изделий" periods="100" form-modifiers="1" synonyms="акциз">
      <variant id="1" fp:ВерФОтч="3.00000" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
      <variant id="2" fp:ВерФОтч="3.00001" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
      <variant id="3" fp:ВерФОтч="3.00002" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
      <variant id="4" fp:ВерФОтч="3.00003" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
      <variant id="5" fp:ВерФОтч="3.00004" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
      <variant id="6" fp:ВерФОтч="3.00005" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
    </format>
    <format id="13" fp:КНД="1151005" shortName="Акцизы на алкогольную продукцию" name="Налоговая декларация по акцизам на алкогольную продукцию, реализуемую с акцизных складов оптовых организаций" periods="100" form-modifiers="1" synonyms="акциз">
      <variant id="1" fp:ВерФОтч="3.00001" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
      <variant id="2" fp:ВерФОтч="3.00002" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
      <variant id="3" fp:ВерФОтч="3.00003" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
      <variant id="4" fp:ВерФОтч="3.00004" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
      <variant id="5" fp:ВерФОтч="3.00005" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
      <variant id="6" fp:ВерФОтч="3.00006" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
    </format>
    <format id="14" fp:КНД="1151006" shortName="Налог на прибыль" name="Налоговая декларация по налогу на прибыль организаций" periods="110" period-modifiers="1" form-modifiers="1">
      <variant id="1" fp:ВерФОтч="2.00001" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
      <variant id="2" fp:ВерФОтч="3.00000" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
      <variant id="3" fp:ВерФОтч="3.00001" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
      <variant id="4" fp:ВерФОтч="3.00002" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
      <variant id="5" fp:ВерФОтч="3.00003" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
      <variant id="6" fp:ВерФОтч="3.00004" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
      <variant id="7" fp:ВерФОтч="3.00005" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
      <variant id="8" fp:ВерФОтч="3.00006" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
      <variant id="9" fp:ВерФОтч="3.00007" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
      <variant id="10" fp:ВерсФорм="5.01" contentType="Xml" ТипИнф="ОТЧЕТНОСТЬ5.00" period-modifiers="100001"/>
      <variant id="11" fp:ВерсФорм="5.02" contentType="Xml" ТипИнф="ОТЧЕТНОСТЬ5.00" period-modifiers="100001"/>
      <variant id="12" fp:ВерсФорм="5.03" contentType="Xml" ТипИнф="ОТЧЕТНОСТЬ5.00" period-modifiers="100001"/>
      <variant id="13" fp:ВерсФорм="5.04" contentType="Xml" ТипИнф="ОТЧЕТНОСТЬ5.00" period-modifiers="100101"/>
    </format>
    <format id="15" fp:КНД="1151020" name="Налоговая декларация по налогу на доходы физических лиц (форма 3-НДФЛ)" shortName="3-НДФЛ" periods="1" form-modifiers="1">
      <variant id="1" fp:ВерФОтч="3.00000" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
      <variant id="2" fp:ВерФОтч="3.00001" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
      <variant id="3" fp:ВерФОтч="3.00002" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
      <variant id="4" fp:ВерФОтч="3.00003" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
      <variant id="5" fp:ВерФОтч="3.00004" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
      <variant id="6" ВерсФорм="5.02" contentType="Xml" ТипИнф="ОТЧЕТНОСТЬ5.00" />
      <variant id="7" fp:ВерсФорм="5.04" contentType="Xml" ТипИнф="ОТЧЕТНОСТЬ5.00" />
      <variant id="8" fp:ВерсФорм="5.05" contentType="Xml" ТипИнф="ОТЧЕТНОСТЬ5.00" />
      <variant id="9" fp:ВерсФорм="5.06" contentType="Xml" ТипИнф="ОТЧЕТНОСТЬ5.00" />
      <variant id="10" fp:ВерсФорм="5.07" contentType="Xml" ТипИнф="ОТЧЕТНОСТЬ5.00" />
    </format>
    <format id="16" fp:КНД="1151021" name="Налоговая декларация о предполагаемомо доходе физического лица (форма 4-НДФЛ)" shortName="4-НДФЛ" periods="1" form-modifiers="1">
      <variant id="1" fp:ВерФОтч="3.00000" contentType="Plain866" fp:ТипИнф="ОТЧЕТНОСТЬНП" />
      <variant id="2" fp:ВерсФорм="5.01" contentType="Xml" ТипИнф="ОТЧЕТНОСТЬ5.00" />
    </format>
